apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
        - name: vite-app
          image: ghcr.io/nirmata/webclient:dirty-testing-34
          imagePullPolicy: Always
          ports:
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
spec:
  selector:
    app: vite-app
  ports:
    - name: http
      protocol: TCP
      port: 8082 
      targetPort: 80
  type: NodePort
